### PR TITLE
Fix Failing Tests for FormInputs

### LINKED ISSUE #115: Fix Failing Tests for FormInputs
- [ ] should emit a value on mount
- [ ] should emit the value when input changes 
- [ ] displays validation error messages when the field is invalid 
- [ ] removes the validation error messages when the field is valid.

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
closes #115 

- change display error
- fix test

### CODE REVIEW

File: src/components/FormInput.vue [hunk 1]
```diff
@@ -11,14 +11,7 @@
...
     >
-      <template v-if="validator && validator.errorCount">
-        <div class="invalid-feedback" v-for="(errors, index) in validator.errors.all()" :key="index">
-          <div v-for="(error, subIndex) in errors" :key="subIndex">
-            {{error}}
-          </div>
-        </div>
-      </template>
-      <div class="invalid-feedback" v-if="error">{{error}}</div>
+    <display-errors v-if="error || (validator && validator.errorCount)" :name="name" :error="error" :validator="validator"/>
```
Comment (chipit24) [inline src/components/FormInput.vue]: I don't think the `v-if` on the `display-errors` component is needed, since the template of that component already contains a `v-if`  (`v-if="displayErrors"`) that seems to accomplish the same thing.

File: tests/unit/FormInput.spec.js [hunk 2]
```diff
@@ -18,15 +24,15 @@ describe('FormInput', () => {
 
   it('should emit a value on mount', () => {
     const wrapper = factory();
-    expect(wrapper.emitted().input).toBeTruthy();
+    expect(wrapper.emitted()).toBeTruthy();
```
Comment (chipit24) [inline tests/unit/FormInput.spec.js]: Is there a specific value that should be emitted? Looking at the component, it's not obvious that a value should be emitted when the component mounts; it seems that functionality comes from the `formatFloatValue` function.

File: tests/unit/FormInput.spec.js [hunk 3]
```diff
@@ -71,39 +76,43 @@ describe('FormInput', () => {
...
-    const requiredText = 'The FormInput field is required.';
     const errorText = 'This field has an error';
     const wrapper = factory({
       name: 'FormInput',
       error: errorText,
       validation: 'required'
     });
-    
+
+    wrapper.setProps({value: "", validation: 'required'});
```
Comment (chipit24) [inline tests/unit/FormInput.spec.js]: It looks like you already set `validation: 'required'` in the factory method above. Is there a reason you need to set it again here?

File: tests/unit/FormInput.spec.js (hunk 2 above)
Comment (marcoAntonioNina) [reply tests/unit/FormInput.spec.js]: Yes you are correct. I'm not sure if any component emits any value on mount.

File: tests/unit/FormInput.spec.js (hunk 3 above)
Comment (marcoAntonioNina) [reply tests/unit/FormInput.spec.js]: yes, I have to remove it from the factory.
