### PR TITLE
Fix date validation

### LINKED ISSUE #108: Validator doesn't correctly validate date
The validator is set up to validate the _date_ type as a date, which is:
> [...] a valid date format which is acceptable by Javascript's Date object.
> https://github.com/skaterdav85/validatorjs#date

However, this fails for the date string `"10/09/2019"`, despite it being accepted by the `Date` object:
```js
new Date('10/09/2019'); // Wed Oct 09 2019 00:00:00 GMT-0400 (Eastern Daylight Time)
```

```js
import Validator from "validatorjs";

let validation = new Validator(
  {
    date: "10/09/2019", // fails validation
    datetime: "10/09/2019 11:00 pm" // passes validation
  },
  {
    date: "date",
    datetime: "date"
  }
);
```

I have set up an example on CodeSandbox here: https://codesandbox.io/embed/amazing-bhabha-zyz5s.

This validation is set up in the `DataFormat.js` file:
https://github.com/ProcessMaker/vue-form-elements/blob/fa5a3a39b279709507e4c8a06f2be6fb057ed069/src/components/mixins/DataFormat.js#L57

One solution to this problem would be to set up a custom validation rule, described at https://github.com/skaterdav85/validatorjs#register-custom-validation-rules.

### PR DESCRIPTION
**Pull request by chipit24**
Fixes #108.

### CODE REVIEW

File: src/dateUtils.js [hunk 1]
```diff
@@ -26,3 +26,7 @@ export function getUserDateFormat() {
 export function getUserDateTimeFormat() {
   return getProcessMakerUserValue('datetime_format') || 'MM/DD/YYYY h:mm A';
 }
+
+export function isValidDate(date, format = getUserDateFormat()) {
+  return moment(date, format).isValid();
```
Comment (JCook21) [inline src/dateUtils.js]: I'm a bit torn about this function. One one level it seems to be a middleman but on another it abstracts away the dependency on moment. What are your thoughts?

Comment (chipit24) [reply src/dateUtils.js]: Good point! The way it's called is, it's passed as a function to the validator:
```
Validator.register('dateFormat', isValidDate, `The :attribute is not a valid date with format ${getUserDateFormat()}`);
```
I'm not sure how I can un-wrap this, as I can't simply pass `moment.isValid`, since it needs to be called from a moment object, and I also need a way to pass the date format. So the best I could do is inline the method, and then test it by calling `validator.passes()`? But we're not really concerned about the validator class.

So I'm fine leaving it like this for now.

Comment (JCook21) [reply src/dateUtils.js]: I think this is fine for now. At the least the abstraction over moment is useful.
